doctrine_migrations:
    dir_name: '%kernel.project_dir%/migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(LOCAL_DATABASE_URL)%'
                server_version: 'mariadb-10.4.11' # maria db stable
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

            remote:
                # configure these for your database server
                url: '%env(REMOTE_DATABASE_URL)%'
                server_version: '8.0' # mysql 8 community
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'Core\Entity'
                alias: Core
            FrontOffice:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/FrontOffice/Entity'
                    prefix: 'FrontOffice\Entity'
                    alias: FrontOffice
            Admin:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Admin/Entity'
                    prefix: 'Admin\Entity'
                    alias: Admin