easy_admin:
  site_name: 'Ecoservice - Back Office'

  formats:
    date: 'Y-m-d'
    time: 'H:i:s'
    datetime: 'Y-m-d H:i:s'

  entities:

    User:
      class: Core\Entity\User
      label: 'Users'
      list:
        title: 'Users'
        fields:
          - id
          - name
          - { property: 'email', type: 'email' }
          - { property: 'is_active', type: 'toggle', label: 'Active?' }
          - { property: 'roles', type: 'json_array' }
          - createdAt
        actions: ['show', 'edit', 'delete']
        dql_filter: 'entity.isDeleted = false'
      show:
        fields:
          - id
          - name
          - { property: 'roles', type: 'json_array' }
          - { property: 'email', type: 'email' }
          - { property: 'is_active', type: 'toggle', label: 'Active?' }
          - createdAt
          - lastLoginAt
          - lastLoginIp
          - lastUserAgent
      form:
        fields:
          - name
          - { property: 'email', type: 'email' }
          - { property: 'passwordHash', type: 'password', label: 'Password' }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: "%security.role_hierarchy.roles.ROLE_FULL_USER%" } }


    Admin:
      class: Core\Entity\Admin
      label: 'Admins'
      list:
        title: 'Admins'
        fields:
          - id
          - name
          - { property: 'email', type: 'email' }
          - { property: 'is_active', type: 'toggle', label: 'Active?' }
          - createdAt
        actions: ['show', 'edit', 'delete']
        dql_filter: 'entity.isDeleted = false'
      show:
        fields:
          - id
          - name
          - { property: 'email', type: 'email' }
          - { property: 'is_active', type: 'toggle', label: 'Active?' }
          - createdAt
          - lastLoginAt
          - lastLoginIp
          - lastUserAgent
      form:
        fields:
          - name
          - { property: 'email', type: 'email' }
          - { property: 'passwordHash', type: 'password', label: 'Password' }
