vich_uploader:
    db_driver: orm # or mongodb or phpcr

    mappings:
        files:
            upload_destination: '%kernel.project_dir%/public/uploads/'
            directory_namer: 'core.helper.upload_namer'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            #chibron
