vich_uploader:
    db_driver: orm # or mongodb or phpcr

    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user_image:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        blog_image:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/blog'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        diy_image:
            uri_prefix: /images/diy
            upload_destination: '%kernel.project_dir%/public/images/diy'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer