vich_uploader:
    db_driver: orm # or mongodb or phpcr

    mappings:
        files:
            uri_prefix: '/uploads'
            upload_destination: '%kernel.project_dir%/public/uploads'
            directory_namer: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

#Admin\Entity\Article:
 #   coverFile:
  #      mapping: files        # required
   #     filename_property: coverName  # required
    #    size: coverSize
     #   mime_type: coverMimeType
      #  original_name: coverOriginalName
       # dimensions: coverDimensions