webpack_encore:
    # The path where Encore is building the assets.
    # This should match Encore.setOutputPath() in webpack.config.js.
    output_path: false
    builds:
        front_office: '%kernel.project_dir%/public/build/front_office'
        admin: '%kernel.project_dir%/public/build/admin'

        # if using Encore.enableIntegrityHashes() specify the crossorigin attribute value (default: false, or use 'anonymous' or 'use-credentials')
        # crossorigin: 'anonymous'

        # Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
        # Available in version 1.2
        cache: '%kernel.debug%'
