---
conf:
    os: "10.2"                      # Choose your debian according to bento boxes (need vagrant destroy & vagrant up)
    private_ip: "192.168.56.111"    # VM IP in your host-only-network
    servername: ecoservice.cum      # Servername and domain for your projects
    org: g4-dev                     # Organisation hosting repo
    projectname: ecs                # repo name with pattern src-{{projectname}}
    debug_playbook: false           # first need vagrant reload !! ENABLE SHARED FOLDERS !! used to debug playbook
    playbook_version: master        # master = stable | versions/beta
    testing_mode: 0                 # test services
    web_path: www                   # change web server if name != local_name
    app_env: dev                    # prod or dev
    ssl: false                      # disable if you can't install a certificate (not working yet)
    nfs_force_disable: yes          # don't wan't nfs enabled because it's slow

vm:
    name: ecoservice                # VM name for Virtualbox (string)
    memory: 2048                    # binary friendly value (int | 2048(min) / 3072 / 4096)
    cpus: 2                         # logical cores of vm (int | 2(min))
    cpuexecutioncap: 80             # virtual cpu, use high value with nfs (int | max: 100)
    natdnshostresolver1: "on"       # perf + (string | on/off)
    natdnsproxy1: "on"              # perf + (string | on/off)
    ioapic: "on"                    # perf + (string | on/off)
