easy_admin:
    entities:
        AbstractCategory:
            class: Admin\Entity\AbstractSluggable
            disabled_actions: ['show','new','delete','edit']
            list:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'slug', template: '@admin/custom-fields/page-link.html.twig', label: 'links.category', route: 'productShow' }

