easy_admin:
    entities:
        AbstractCategory:
            class: Admin\Entity\AbstractCategory
            disabled_actions: ['show','new','delete','edit']
            list:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
                    - { property: 'slug', template: '@admin/custom-fields/category-link.html.twig', label: 'links.category', route: 'productCategoryList' }

