easy_admin:
    entities:
        Diy:
            # TODO: traductions
            class: Admin\Entity\Diy
            image_base_path: '%kernel.project_dir%/public/uploads/'
            list:
                title: 'diy.title'
                fields:
                    - { property: 'name', label: 'Titre' }
                    - { property: 'image', label: 'Cover', type: 'image', base_path: '%ecs.path.blog_covers%' }
                    - { property: 'difficulty', label: 'difficulty', type: range}
                    - { property: 'slug', template: '@admin/custom-fields/page-link.html.twig', label: 'links.diy', route: 'diyShow' }
                actions: ['edit', 'delete']
            show:
                fields:
                    - { property: 'name', label: 'Titre' }
                    - { property: body, label: Contenu, type: html }
                    - { property: 'difficulty', label: 'difficulty', type: range }
                    - { property: 'image', label: 'Cover', type: 'image', base_path: '%ecs.path.blog_covers%' }
                    - { property: 'slug', template: '@admin/custom-fields/page-link.html.twig', label: 'links.diy', route: 'diyShow' }

            form:
                fields:
                    - { property: 'name', label: 'Titre' }
                    - { property: 'body', type: 'text_editor', label: 'Contenu', type_options: { trim: true } }
                    - { property: 'difficulty', label: 'difficulty', type: range}
                    - { property: 'imageFile', label: 'Cover', type: 'vich_image', type_options: { required: false } }
