easy_admin:
    entities:
        Article:
            class: Admin\Entity\Article
            image_base_path: '%kernel.project_dir%/public/uploads/'
            list:
                title: 'Articles'
                fields:
                    - title
                    - { property: 'file', label: 'Cover', type: 'image', template: 'bundles/EasyAdminBundle/customs/field_vich_image.html.twig' }
                actions: ['edit', 'delete']
            show:
                fields:
                    - title
                    - { property: body, label: Contenu, type: html }
                    - { property: 'file', label: 'Cover', type: 'image' }
            form:
                fields:
                    - 'title'
                    - { property: 'body', type: 'text_editor', label: 'Contenu', type_options: { trim: true } }
                    - { property: 'file', label: 'Cover', type: 'vich_image' }
