easy_admin:
    entities:
        CmsPage:
            # TODO: traductions
            class: Admin\Entity\CmsPage
            image_base_path: '%kernel.project_dir%/public/uploads/'
            list:
                title: 'Articles'
                fields:
                    - { property: 'name', label: 'Titre' }
                    - { property: 'image', label: 'Cover', type: 'image', base_path: '%ecs.path.blog_covers%' }
                    - { property: 'slug', template: '@admin/custom-fields/page-link.html.twig', label: 'links.page_cms', route: 'cmsShow' }
                actions: ['edit', 'delete']
            show:
                fields:
                    - { property: 'name', label: 'Titre' }
                    - { property: body, label: Contenu, type: html }
                    - { property: 'imageFile', label: 'Cover', type: 'image', base_path: '%ecs.path.blog_covers%' }
            form:
                fields:
                    - { property: 'name', label: 'Titre' }
                    - { property: 'body', type: 'text_editor', label: 'Contenu', type_options: { trim: true } }
                    - { property: 'cmsCategories', type: 'easyadmin_autocomplete' }
                    - { property: 'imageFile', label: 'Cover', type: 'vich_image', type_options: { required: false } }
