# Add pages for the differents spaces here (correspond to webpack entries)
- name: front_office
  pages:
    - { entry: products, ext: ts }
    - homepage # pas obliger de préciser l'extenstion de l'entrée (si on a une valeur par défault)
    - accounting
    - company

- name: easyadmin
  pages:
    - js/app
