#index:
#    path: /
#    controller: FrontOffice\Controller\DefaultController::index

product_show:
  path: /product
  controller: FrontOffice\Controller\ProductController::show
  requirements:
    slug: '[a-zA-Z1-9\-]+'

basket_show:
  path: /basket
  controller: FrontOffice\Controller\BasketController::show

basket_add:
  path: /basket/add/{id}
  controller: FrontOffice\Controller\BasketController::add
  requirements:
    id: '\d+'

basket_remove:
  path: /basket/remove/{id}
  controller: FrontOffice\Controller\BasketController::remove
  requirements:
    id: '\d+'

basket_update:
  path: /basket/update
  controller: FrontOffice\Controller\BasketController::update

user_account:
  path: /user/account
  controller: FrontOffice\Controller\RegistrationController::account

user_edit-address:
  path: /user/account/edit-address
  controller: FrontOffice\Controller\RegistrationController::editAddress

user_orders:
  path: /user/account/orders
  controller: FrontOffice\Controller\RegistrationController::orders

user_order:
  path: /user/account/order/{id}
  controller: FrontOffice\Controller\RegistrationController::order
  requirements:
    id: '\d+'

paypal_checkout:
  path: /checkout/paypal-checkout
  controller: FrontOffice\Controller\Payments\PaypalController::paypalCheckout

paypal_payment:
  path: /checkout/paypal-payment
  controller: FrontOffice\Controller\Payments\PaypalController::paypalPayment

checkout_address:
  path: /checkout/address
  controller: FrontOffice\Controller\CheckoutController::address

checkout_shipping:
  path: /checkout/shipping
  controller: FrontOffice\Controller\CheckoutController::shipping

checkout_summary:
  path: /checkout/summary
  controller: FrontOffice\Controller\CheckoutController::summary

checkout_payment:
  path: /checkout/payment
  controller: FrontOffice\Controller\CheckoutController::payment
