imports:
    - { resource: parameters.yaml }
    #- { resource: pages.yml }

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    website_name: Ecoservice

    # perf
    container.dumper.inline_factories: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $emailFrom: '%env(MAILER_URL)%'
            $emailName: 'Ecoservice'

    Core\:
        resource: '../src/Core/*'
        #exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    core.admin:
        class: Core\Service\AdminService
        public: true

    core.mailer:
        class: Core\Service\MailerService
        public: true

    core.user:
        class: Core\Service\UserService
        public: true

    Fixtures\DataFixtures\:
        resource: '../fixtures/DataFixtures'
        tags: ['doctrine.fixture.orm']

    Admin\Controller\:
      resource: '../src/Admin/Controller'
      tags: ['controller.service_arguments']
      #arguments:
          #- '@core.admin' # need to wire manually because we use EasyAdmin controller

    FrontOffice\Controller\:
        resource: '../src/FrontOffice/Controller'
        tags: ['controller.service_arguments']

    admin.security.login_form_guard:
        class: 'Admin\Security\LoginFormGuard'

    front_office.security.login_form_guard:
        class: 'FrontOffice\Security\LoginFormGuard'
