easy_admin:
    entities:
        Settings:
            class: Admin\Entity\Settings
            label: 'Settings'
            #controller: Admin\Controller\SettingsController
            disabled_actions: ['show', 'list', 'new', 'delete']
            form:
                title: 'settings.homepage'
                fields:
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'headlineCmsPages', type: 'easyadmin_autocomplete', label: 'settings.cmsPages', dql_filter: 'entity.isActive = true' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    #- { property: 'homeProducts', type: 'easyadmin_autocomplete', label: 'settings.products', dql_filter: 'entity.isActive = true' }
                    - { property: 'homeDiys', type: 'easyadmin_autocomplete', label: 'settings.diy', dql_filter: 'entity.isActive = true' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'footerCmsPages', type: 'easyadmin_autocomplete', label: 'settings.footer_pages', dql_filter: 'entity.isActive = true' }
                    # if you want to add products when creating categories, add the 'by_reference' option
                    # - { property: 'products', type_options: { by_reference: false } }
