on: [pull_request]

name: Run composer testsuite
jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --prefer-dist --no-scripts -q -o;

    # if the clear cache fail it's because a lockfile/ json isn't updated

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
